name: quran_projek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  get: ^4.6.5
  get_cli: ^1.8.1
  lottie: ^1.4.3
  just_audio: 0.9.29
  sqflite: 2.1.0+1
  path_provider: 2.0.11
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lotties/
  uses-material-design: true

